### PR TITLE
Fixed PuLP compatibility issue

### PR DESCRIPTION
**Pull request by thomasckng**
Fixed PulP compatibility issue mentioned in #430.

### CODE REVIEW

**Comment by dfm** [comment]
Thanks!!

**Comment by matiscke** [comment]
I believe the github workflow defaults to installing the latest showyourwork version available on PyPi. How can I use a showyourwork version including this fix before a new version is released?

**Comment by thomasckng** [comment]
@matiscke you can specify the version it installs in the `.github/workflows/build.yml` file of your paper repo. This is also mentioned in another issue https://github.com/showyourwork/showyourwork/issues/406#issuecomment-1803026381. This will use the latest version of showyourwork in the main branch.

**Comment by matiscke** [comment]
right, I totally forgot about the `showyourwork-spec` variable - thanks a lot for the reminder Thomas!

**Pull request merged**
