### PR TITLE
Add #419 to known issues

### PR DESCRIPTION
**Pull request by rmnldwg**
As [suggested by HealthyPear](https://github.com/showyourwork/showyourwork/issues/419#issuecomment-2434695335), I added a description of issue #419 to the list of known issues in the docs.

Note that I also added the `hacks` library to the dependencies in the `docs/environment.yml` file, because otherwise `make html` would not have worked.

### CODE REVIEW

**Comment by HealthyPear** [comment]
> Note that I also added the hacks library to the dependencies in the docs/environment.yml file, because otherwise make html would not have worked.

This should serve the same purpose of #480 , though I do not understand here: the `hacks` module that `conf.py` imports is not a conda package, but a local file in the `docs` directory (this is why I used `sys`). How does this work here?

**Comment by rmnldwg** [comment]
Oh, I see... Sorry, I didn't even consider that it could be a local file and just assumed `hacks` was a package.

So, how does this work now? Should I add the changes from #480 to this pull request?

**Comment by HealthyPear** [comment]
Technically that change is not needed for this PR as the documentation compiles succesfully online (probably some different setting on readthedocs). #480 is needed for local compilation

**Comment by HealthyPear** [comment]
@rmnldwg this branch fell a bit behind with the default branch

before merging I suggest to cleanup its history by doing this:

- from your branch call `git rebase -i HEAD~3`, this should open your default editor
- change the 1st and 3rd commit from `pick` to `drop`
- save and close the editor
- `git push --force`

then I will rebase this branch on top of the `main` branch and merge it

**Comment by rmnldwg** [comment]
I cleaned up the history as you suggested and rebased it onto the updated `main` branch.

**Comment by HealthyPear** [comment]
Thanks for this!

**Pull request merged**
